version: '3.8'
name: 'snackShack'

services:
  snackShack:
    image: ghcr.io/qwacko/snackshack:master
    environment:
      - DATABASE_FILE=/app/db/db.db
      - ORIGIN=https://www.example.com
      - PORT=3000
      - ALLOW_SIGNUP=false
      - FIRST_DAY_OF_WEEK="SUNDAY"
      - ORDER_DAY="SUNDAY"
    volumes:
      - ./db/:/app/db
    ports:
      - 3000:3000
    restart: unless-stopped
