version: '3.8'
name: 'snackShack'

services:
  snackShack:
    image: ghcr.io/qwacko/snackshack:master
    environment:
      - DATABASE_FILE=/app/db/db.db
      - UPLOAD_DIR=/app/uploads
      - BACKUP_DIR=/app/backups
      - ORIGIN=https://www.example.com
      - PORT=3000
      - ALLOW_SIGNUP=false
      - FREQUENCY=WEEKLY
      - START_DAY=0
      - ORDER_LEAD=2
      - DAYS_TO_ALLOW_ORDERING=7
    volumes:
      - ./db/:/app/db
      - ./uploads/:/app/uploads
      - ./backups/:/app/backups
    ports:
      - 3000:3000
    restart: unless-stopped
